version: '3'
services:
  frontend:
    container_name: frontend-container
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"

  backend:
    container_name: backend-container
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
