version: '3.7'
services:
  frontend:
    container_name: frontend-container
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    container_name: backend-container
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
