"use client";
import { QueryProvider } from "@/components/query-provider";
import Navbar from "@/components/navbar";
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [expandNavbar, setExpandNavbar] = React.useState(false);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <QueryProvider>
          <Navbar
            expandNavbar={expandNavbar}
            setExpandNavbar={setExpandNavbar}
          />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
